# Setup
title: "David Reed"
author:
  name: David Reed
  url: "https://ktema.org"
tagline: "Salesforce, DevOps, Ancient Greek"
sidebar_blog_link: /blog

remote_theme: fongandrew/hydeout
plugins:
  - jekyll-feed
  - jekyll-seo-tag

paginate: 5
paginate_path: "/blog/page:num/"

links:
  github: https://github.com/davidmreed
  twitter: https://twitter.com/aoristdual
  linkedin: https://www.linkedin.com/in/davidreed-salesforce/
  sfse: https://salesforce.stackexchange.com/users/46017/david-reed
  email: mailto:david@ktema.org
  tbc: https://trailblazer.me/id/davidmreed
  mastodon: https://mastodon.technology/web/@aoristdual
