base_url = "https://ktema.org"
compile_sass = false
build_search_index = false
generate_feed = true
feed_filename = "feed.xml"
theme = "datum"

taxonomies = [
    { name = "series", feed = false, render = false }
]

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "gruvbox-dark", filename = "syntax-theme-dark.css" },
  { theme = "inspired-github", filename = "syntax-theme-light.css" },
]

[extra]

site_owner_name = "David Reed"
site_title = "David Reed"
use_icons = true
use_tocs = false
use_social_sharing = true
timeline_length = 5

[extra.contact]
order = ["email", "github", "mastodon", "twitter", "linkedin", "sfse", "tbc"]

[extra.contact.email]
link = "mailto:david@ktema.org"

[extra.contact.github]
link = "https://github.com/davidmreed"

[extra.contact.twitter]
link = "https://twitter.com/aoristdual"
username = "aoristdual"

[extra.contact.linkedin]
link = "https://www.linkedin.com/in/davidreed-salesforce/"

[extra.contact.tbc]
link = "https://trailblazer.me/id/davidmreed"
name = "Trailblazer Community"
icon = "brands/salesforce"

[extra.contact.sfse]
link = "https://salesforce.stackexchange.com/users/46017/david-reed"
name = "Salesforce Stack Exchange"
icon = "brands/stack-exchange"

[extra.contact.mastodon]
link = "https://fosstodon.org/web/@aoristdual"
